### ISSUE TITLE
Mirror showing as offline on the Google home app

### ISSUE THREAD

**Issue by richa184** [bugsounet/MMM-GoogleAssistant#108]
Hi, I've installed Google assistant on my magic mirror (along with assistant2display and mmm-spotify). The assistant works well, but I want to control my mirror via the Google home app. Currently my mirror shows as offline on the app - I've attached a screenshot below. 
![Screenshot_20200728_164901_com google android apps chromecast app](https://user-images.githubusercontent.com/60963876/88689382-4ebe9f80-d0f2-11ea-8b52-464b3f4591fe.jpg)

**Comment by bugsounet** [comment]
Hi,

Sure because MMM-GoogleAssistant don't comunicate with google server on standby mode
this module is an SDK project (+/- demo) and it don't know what is the mirror state
but maybe you can control it with a recipe and actions code
I can't offer any other help for your issue because i don't use it really :(

but if you resolve it, give me a feed back with tutorial ;)
